apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caddy-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: caddy-config
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
